### ISSUE TITLE
Write blog post about creating your own policy that uses sigstore primitives

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/kubewarden.io#83] opened 2022-04-22 13:10 UTC

**Comment by flavio** [comment] 2022-04-29 13:11
Duplicate of https://github.com/kubewarden/kubewarden.io/issues/84

**Comment by flavio** [comment] 2022-04-29 13:24
Sorry, it's two different issues.

**Comment by flavio** [comment] 2022-08-10 13:04
Not super important, cleaning up

**Closed by flavio** 2022-08-10 13:04 UTC
Labels: blog
